### ISSUE TITLE
Plugin system for rendering custom Liquid tags

### ISSUE THREAD

**Issue by DrSensor** [voraciousdev/ink-mde#2]
I think a plugin system for rendering user-defined liquid tags is necessary to solve https://github.com/writewithocto/octo/issues/37 since DEV by default support [several liquid tags](https://dev.to/p/editor_guide#liquidtags)

**Comment by voraciousdev** [comment]
@DrSensor this is a good point! I'll dig into it when I get a chance.

**Comment by voraciousdev** [comment]
This relates to #24

**Comment by voraciousdev** [comment]
This is now possible via #32. While it doesn't add support for liquid tags directly, it can be implemented as a custom [CodeMirror extension](https://codemirror.net/docs/guide/).
